version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main

jobs:
  build:
    working_directory: ~/starWarsShipApp
    docker:
      - image: cimg/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: apt-get update
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json"}}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json"}}
          paths:
            - ./node_modules
  deploy:
    docker:
      - image: cimg/node:10.16.3
    steps:
      - run:
          name: deploy-app
          command: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "export SERVER=\"$SERVER\"; export PRIVATE_KEY=\"$PRIVATE_KEY\";  "rm -rf starWarsShipApp/; git clone https://github.com/mmNCI/starWarsShipApp.git; source starWarsShipApp/deploy.sh
