version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - main

      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - main

jobs:
  build:
    working_directory: ~/starWarsShipApp
    docker:
      - image: cimg/node:20.11
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: check-sudo
          command: which sudo
      - run:
          name: update-npm
          command: sudo apt-get update
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json"}}
      - run:
          name: install-npm
          command: sudo npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json"}}
          paths:
            - ./node_modules
      - run:
          name: docker-login
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: build-docker-image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: publish-docker-image
          command: docker push $IMAGE_NAME
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json"}}
          paths:
            - ./node_modules
  test:
    docker:
      - image: cimg/node:20.11
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json"}}
      - run:
          name: install-npm
          command: sudo npm install
      - run:
          name: test-run
          command: sudo npm run test
  deploy:
    docker:
      - image: cimg/node:20.11
    steps:
      - run:
          name: deploy-app
          command: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "export SERVER=\"$SERVER\"; export PRIVATE_KEY=\"$PRIVATE_KEY\"; rm -rf starWarsShipApp/; git clone https://github.com/mmNCI/starWarsShipApp.git; source starWarsShipApp/deploy.sh"
